### PR TITLE
updating references to interface classes

### PR DESCRIPTION
**Pull request by syclik**
#### Summary:

Updates interface due to renaming of files in Stan's C++ API.

#### Intended Effect:

Fixes the interface due to stan-dev/stan#1569

#### How to Verify:

Build

#### Side Effects:

This should fix the renaming of files in the C++ api.

#### Documentation:

None.

#### Reviewer Suggestions: 

@ariddell , but this should not go in before https://github.com/stan-dev/stan/pull/1572

### CODE REVIEW

**Comment by syclik** [comment]
Allen -- you might not want to merge it yet. The Stan branch hasn't fully
merged yet.

(or... you can have faith that it will be merged in short order)

**Comment by ariddell** [comment]
I saw the tests passing so I went ahead. Should they not have passed?

**Comment by syclik** [comment]
They do pass. The Stan branch isn't "develop" yet.

Don't worry about it. Next time I'll just hold off on creating a pull
request until it gets into Stan's develop branch.

**Comment by ariddell** [comment]
oh! That's fine. develop can point to whatever version of Stan it wants!

**Comment by ariddell** [comment]
@syclik This is for 2.7.1, right? I reverted this for a hotfix.

**Pull request merged**
