### PR TITLE
Add option to disable diagnostics after sampling

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Add option to disable check_mcmc_diagnostics in sampling function

#### Intended Effect:

If given as `check_diagnostics=False`, no diagnostics is run after sampling is done.

#### How to Verify:

`fit = model.sampling()`
`fit = model.sampling(check_diagnostics=False)`

#### Side Effects:

None

#### Documentation:

Docstring updated.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
@ariddell, do you know what is wrong with the appveyor? It fails to install pip?

**Comment by ariddell** [comment]
With luck #459 fixes it.

**Comment by ariddell** [comment]
Nevermind. I see that you already added a patch. I merged it.

**Comment by ahartikainen** [comment]
If one does fixed_param / samples 1 or let's say <10 samples.

Or runs 100 model and want's to do diagnostics later.

**Comment by ariddell** [comment]
It's the computational cost of checking n_eff that's the issue with 100 models (or very large models), right? (I don't see a problem with generating error messages in general or for fixed_param in particular.)

If someone is running 100 models or very large models though, they surely can wait an extra minute (after waiting many minutes or many hours) for the n_eff calculation. It's not that slow. And it will be faster once it gets implemented in C++ in stan::services.

On RStan alignment: should we at least align the function and parameter names to check_hmc_diagnostics (so change check_mcmc_diagnostics and check_diagnostics to the term that RStan uses)?

**Comment by ariddell** [comment]
Nice. This all seems reasonable. I'm sure @betanalpha will be happy to see the checks being applied automatically.

**Comment by ariddell** [comment]
I think there was consensus on dropping permuted going forward. Perhaps we should not even support it with pandas dataframes? If people wanted permuted results they can use the normal extract method.

**Comment by ariddell** [comment]
LGTM.

**Comment by Bonnevie** [comment]
Speedwise, running really small sample runs (for testing purposes) with ~100 samples, taking 1 second, is then followed by 48 seconds of diagnostics calculation in my setup.

**Comment by ahartikainen** [comment]
Everything looks good. I will merge this.

**Pull request merged**
