### PR TITLE
feat: Scalar numpy dtypes to json

### PR DESCRIPTION
**Pull request by ahartikainen**
This PR sanitizes numpy integer and float values to be JSON compatible.

Fixes #226

### CODE REVIEW

**Comment by riddell-stan** [comment]
This adds some complexity to the function.

I'd like to understand the scope of the problem first. Does np.int32 get serialized? Is it just np.int64 that has a problem?

Is this related to the fact that JSON does not support 64-bit integers?

**Comment by riddell-stan** [comment]
Stan doesn't even support 64 bit integers. ("Stan uses 32-bit (4-byte) integers for all of its integer representations.")

I think we should exhaustively describe what is allowed as `data`. We can make use of the new `typing.TypedDict` to do this. (https://docs.python.org/3/library/typing.html#typing.TypedDict).

**Comment by riddell-stan** [comment]
Here's my proposed type for the `data` argument:

```python
from typing import Dict, Union, List                                                                                                                         
Value = Union[int, float]
Data = Dict[str, Union[Value, List[Value], List[List[Value]], np.ndarray]]
```
If someone wants to pass a List of Lists of Lists... it will work. We can't write the type for it yet because mypy doesn't support recursive definitions.

@ahartikainen if you want to validate the ints (e.g., making sure ints are 32-bit) or the ndarray, that should be a separate PR. I would prefer that we wait until users report specific problems and then solve the problems one by one.

**Comment by ahartikainen** [comment]
It is not that users actually try to give a number that needs 64bits, but that is common type used in numpy arrays. E.g. I had this problem while getting a number from xarray object. (I can send the link for the example).

Same goes float32. 64bit floats are usually default, but there are cases when people get 32bit floats.

Also, in the end, we send python ints/floats (64bit?) to httpstan and that get transformed back to 32bit ints / 64bit floats (-> cython).

**Comment by riddell-stan** [comment]
This is a complex issue. We haven't had a discussion about what permissible `data` dictionaries should look like. In theory, we could accept all sorts of things (e.g., `xarray`s).

I feel strongly that we should explicitly specify what is allowed rather than leaving it unclear. This is in keeping with the spirit of Python ("explicit is better than implicit"). I've created a [PR](https://github.com/stan-dev/pystan/pull/230) to document the existing allowable types.

Right now we allow `nparray`s of int64 because tolist() converts them to normal Python integers. I can see the argument against doing this: Stan doesn't allow int64, only int32. The conservative approach would be to only allow Python floats, Python ints, and Python (nested) lists of ints or floats. So users would have to convert NumPy arrays and xarrays to these formats (with tolist()). A slightly less conservative approach would be to also allow the default numpy arrays (float64 and int64). This is the behavior right now.

Expanding allowable types would, I think, increase the maintenance burden. But perhaps that would be worth it.

I'm not sure expanding allowable types requires a design document. Expanding allowable types does, I think, require broader discussion and concrete examples of users trying to use these types. Submitting these pull requests without concrete examples of problems/bugs is not helpful—it risks wasting developer time solving problems which do not affect more than one person. I know I've been guilty of submitting pull requests which are not associated with specific problems myself—but I'm trying very hard to stop doing it.

**Comment by ahartikainen** [comment]
Apparently one can use `.tolist` for ints too

https://github.com/stan-dev/cmdstanpy/pull/356

    np.int32(3).tolist() == 3

**Comment by riddell-stan** [comment]
I'm closing this because PR #230 fixed the underlying issue #225. PyStan does not currently support the use of scalar numpy types. Opening a new issue makes sense, I think. Something with the title "PyStan's range of supported types is to restrictive".

I don't see any urgency to solve this because developers will be alerted to the issue when they use `mypy` or read the documentation. Users who find the current behavior problematic can use cmdstanpy.

In my view, not supporting scalar numpy types is a feature, not a bug:
1. Users should be careful about the types they use. Stan `int`s are not Python `int`s which are not `numpy.int32`s. Users need to bring some awareness of this when they write code.
2. The `Data` type is concise and easy to read. Adding new types to the type will make things more difficult to read.

**Pull request closed without merging**
