### PR TITLE
[Docs] Logging

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Add instructions for logging module. Contains a simple example how to save output to a file.

#### Intended Effect:

Enable user to output messages to file.(or any other destination)

#### How to Verify:

Save output to logfile.

#### Side Effects:

Disables output if users wants that.

#### Documentation:

Added logging section.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Other format are also ok.

I still need to test the filehandler is working correctly.

**Comment by ahartikainen** [comment]
I believe there should be NullStream for the root logger, so then the setlevel would work. Apparently root is always set to Warning.

**Comment by riddell-stan** [comment]
You mean ``NullHandler``? We add that in ``__init__.py``.

https://github.com/stan-dev/pystan/blob/6c557cf53d833939651a2bb0cfe89b4f166db709/pystan/__init__.py#L16

**Comment by ahartikainen** [comment]
Yes, `NullHandler` for the example (before pystan is imported)

**Comment by riddell-stan** [comment]
This all looks good. I wish we had a mature package which uses pystan as a library -- then we'd know what to do based on experience.

(My suspicion is that an application using a pre-compiled model and using pystan purely as a library would want to silence all PyStan logging output.)

**Comment by ahartikainen** [comment]
Now, this is working as intended. 

If `verbose=True` for `StanModel` it will still print stuff from Cython to stdout. I don't know if there is a way to grab that. 
Some wrapper for function that would grab prjmts, warnings and exceptions and use logging to output them (and then raise exception if needed)

**Pull request merged**
