### PR TITLE
Add warning for plotting

### PR DESCRIPTION
**Pull request by ahartikainen**
Also call permuted=False

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by riddell-stan** [comment]
LGMT. (maybe squash the fixup commit?)

**Comment by ahartikainen** [comment]
@riddell-stan are you ok with the newer numpy?

**Comment by ariddell** [comment]
What's the reason for the bump? If it's only in continuous integration scripts then that's fine. I wouldn't want to change it in the general requirements without warning people. (I'm sure a few people are using this on ancient Centos/RHEL machines.)

**Comment by ahartikainen** [comment]
It is for CI. We could go back with matplotlib.

**Comment by ahartikainen** [comment]
I think I will merge this now. When ArviZ is released and we remove plotting, we could do plot testing in different environment (e.g. py36 only) and test 2.7 with specific old numpy.

**Pull request merged**
