### PR TITLE
DOC: update release notes for 2.18

### PR DESCRIPTION
**Pull request by riddell-stan**
If there are no objections, PyStan 2.18.0.0 will be released tomorrow, 2018-08-13.

### CODE REVIEW

**Comment by ahartikainen** [comment]
Hi, I'm making small addition to lib still.

DOC: How to enable threading + misc.py function for default gxx.

I will add that this is not working with Windows (tested and it will crash). Apparently, this does work with CmdStan where it probably fails silently at exit.

**Comment by ahartikainen** [comment]
Hi, should we add info about the `pystan.diagnostics`?

    - `pystan.diagnostics` was implemented. Thanks @jjramsey

**Comment by riddell-stan** [comment]
I'll add the diagnostics note right now.

I'll wait for the threads PR then. We could also release now and make another release in a few weeks when your patch is done.

**Comment by ahartikainen** [comment]
I think we can merge the patch now (cancel the ci) and then wait for this to compile ready?

It is just a small function and docs. We can send people there when they start to ask how to use threads.

**Comment by riddell-stan** [comment]
There's no harm in waiting. We can make a release when it's ready.

**Pull request merged**
