### PR TITLE
Evaluate logprob without sampling

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Enables user to evaluate LogProb without the sampling step.

#### How to Verify:

Run tests

#### Side Effects:

None

#### Documentation:

Needs updating

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by riddell-stan** [comment]
Things will work differently in PyStan 3. Do we want to introduce this new feature now?

**Comment by ahartikainen** [comment]
I put this to experimental if there are people who want to use scipy optimizers and are not too experienced with PyStan. E.g. some fbprophet users.

But it is not something we "fully" supp ot  

PyStan 3 needs a better interface.

**Comment by riddell-stan** [comment]
By PyStan 3's interface, I mean the planned interface (which is not yet fully implemented): https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers , which will closely match RStan 3's.

It seems like this PR provides the sort of feature that should be in fbprophet or another package. The reasoning here is straightforward: the fewer lines of code that exist in pystan, the less there is to maintain with scarce resources.

We can also add a description of this approach to the documentation. That's another alternative.

With all that said, if you want this in PyStan 2.x, feel free to merge it.

**Comment by ahartikainen** [comment]
Yes, we can skip this PR. One can always copy this (or from discourse)

**Pull request closed without merging**
