### PR TITLE
Remove pystan.stan from README.rst and other places in documentation

### PR DESCRIPTION
**Pull request by randommm**
From what is proposed on issue #330, removinh `pystan.stan` from pystan Github repository homepage would be a good start.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Do we have any opinions on naming?

    sprogram
    program
    dprogram

**Comment by randommm** [comment]
Good point. I thought of leaving just `sm`, but since he said that will 
be called Stan Program in future so I tryed to predict the naming. Also 
thought of helping with the documentation, but there is a whole section 
about avoiding model recompilation which I don't how should be handled 
since it loses its meaning once `stan.fit` is out of the game on the 
previous sections.

**Comment by ariddell** [comment]
Let's keep it "model" for now, otherwise it's a bit confusing. I think we want to do the 's/model/program/' all at once and across all interfaces. Hopefully it will be done when we harmonize variable names and everything else.

**Comment by randommm** [comment]
OK, I removed all the references to `pystan.stan` I could find, trying to adapt the text as most as possible. Should the API documentation of it also include a deprecation note?

**Comment by ariddell** [comment]
Great. Thanks for this!

**Comment by ariddell** [comment]
I'm not sure about the deprecation schedule. I definitely know that we want to discourage the use since we want to separate models and fits for all sorts of reasons (e.g., they have different methods, they need to be pickled separately, ...)

**Pull request merged**
