### PR TITLE
1-based indexing

### PR DESCRIPTION
**Pull request by ahartikainen**
Start indexing with 1 for `fit.flatnames`.

#### Summary:

Starts indexing with 1.

#### Intended Effect:

Correct indices for `fit.summary` and `fit.stansummary`

#### How to Verify:

`print(fit)`

#### Side Effects:

Are these used other than naming parameters.

#### Documentation:

Needs to be checked.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ariddell** [comment]
Is this going to change the printed summaries?

**Comment by ahartikainen** [comment]
I first tried to rebase, but github did not like it, so I did `pull`before `push`.

I removed 2 lines (+ 2 comment lines) from pystan/misc.py that changed base for the pandas dataframe manually. In this PR, it will get the names straight from the `fit.flatnames`.

**Comment by ariddell** [comment]
I'm happy to do the rebase for the sake of a clean history.

As long as things are consistent, I'm fine with this. Thanks for everyone's work on this!

**Comment by ahartikainen** [comment]
@ariddell do you know how to cancel all those commits? If you do, you can go and cancel them (this one is ok a41a32b) and then do the rebase --> edit the pystan/mics.py

I can also close this and make a new one with clean commit history.

**Comment by ariddell** [comment]
If you can fix things with a new PR you can fix this one.

- Create a new temporary branch even with develop.
- Cherry-pick (``git cherry-pick``) the commit you want.
- Delete the old branch
- Rename the temporary branch to the old branch
- Force push the branch to the PR branch.

You could also do an interactive rebase but that's about as much work.

Of course, if you're doing this from your iPhone, I have no idea how you
do this :)

If you have any trouble I'm happy to do it.

**Comment by ahartikainen** [comment]
It worked nicely.

I have android + terminal 😆  so everything works normally, but this one I did with my mac.

**Comment by ariddell** [comment]
You're kidding me. You did this on a smartphone?

Is this ready to merge?

**Comment by ahartikainen** [comment]
I could have done it with my phone (this time I used real keyboard).

My setup is:

Termux => git + vim + clang + python + hackers keyboard

This is ready. Waiting for the tests to finish.

**Comment by ahartikainen** [comment]
Looks good. I did one more readthrough and I didn't find anything that could fail.

I will merge this now.

**Pull request merged**
