### PR TITLE
[WIP] Ship CVODES with PyStan

### PR DESCRIPTION
**Pull request by ariddell**
This is a work in progress. If you install pystan using the branch ``feature/cvodes-support`` you should be able to use functionality in Stan which requires CVODES.

See #209

### CODE REVIEW

**Comment by ariddell** [comment]
Just added the test (which should fail). Will work on this soon.

**Comment by ariddell** [comment]
This can be done (and was done previously for libstan) with ``distutils.command.build_clib``.

**Comment by ariddell** [comment]
This branch should work but there's a problem which needs to be addressed before merging. Because distutils has no way of installing libraries compiled with ``build_clib``, there's no way to link against the compiled cvodes library. This means cvodes code must be compiled with each model, making model compilation about 10% longer.

Numpy's ``install_clib`` machinery should be used. See https://github.com/numpy/numpy/blob/master/numpy/distutils/core.py

**Comment by bob-carpenter** [comment]
@seantalts:  Do you have any ideas how to deal with the build/install issues from Python?  It'd be nice to get CVODES working on PyStan for 2.16.

**Comment by ariddell** [comment]
I think I know vaguely what to do. I'll try working a bit more on this tomorrow. I agree it would be good to have this shipped.

I will add that this branch works by itself, if people (e.g., @MichaelClerx) do want to use CVODES right now.

**Comment by MichaelClerx** [comment]
@ariddell where can I find the modules `_winreg`, `win32api` or `win32con` required for build?
(And are they really required for building on a linux system?)

**Comment by ariddell** [comment]
@MichaelClerx where are you seeing those errors?

If you're trying to use this branch you might try using a fresh virtualenv.

**Comment by MichaelClerx** [comment]
I've removed the pip installed version of pystan, cloned the repo, switched to the appropriate branch and tried to run "python setup install". Almost immediatly, it shows:

```
running install
running build
running build_py
running build_ext
building 'pystan._api' extension
C compiler: gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC

compile options: '-DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math_2.15.0/ -Ipystan/stan/lib/stan_math_2.15.0/lib/eigen_3.2.9 -Ipystan/stan/lib/stan_math_2.15.0/lib/boost_1.62.0 -Ipystan/stan/lib/stan_math_2.15.0/lib/cvodes_2.9.0/include -I/usr/include/python2.7 -c'
extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized'
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
gcc: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp
gcc: error: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
gcc: error: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: Command "gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -Ipystan/stan/src -Ipystan/stan/lib/stan_math_2.15.0/ -Ipystan/stan/lib/stan_math_2.15.0/lib/eigen_3.2.9 -Ipystan/stan/lib/stan_math_2.15.0/lib/boost_1.62.0 -Ipystan/stan/lib/stan_math_2.15.0/lib/cvodes_2.9.0/include -I/usr/include/python2.7 -c pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp -o build/temp.linux-x86_64-2.7/pystan/stan/src/stan/lang/grammars/expression_grammar_inst.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized" failed with exit status 1
```

**Comment by ahartikainen** [comment]
Hi, did you remember to use `--recursive` keyword to download stan source?

**Comment by ariddell** [comment]
I'm going to make a separate cvodes Github release (just a tarball) for 2.17. I'll add some documentation about how you can pip install the tarball. I realize it's a short-term fix. The real solution requires careful navigation of the minefield that is distutils. And given that distutils is currently being revised (finally!) by the Python people (look at the last few PEPs), I'm tempted to put it off for now.

**Comment by ariddell** [comment]
I've been looking at the pytorch [setup.py](https://github.com/pytorch/pytorch/blob/master/setup.py) and it looks like they do build a bunch of libraries before wrapping it all up in a wheel. PyStan did, at one point, do something like this, before stan could be built header-only.

I'm hesitating here because the maintenance burden is rather large. Python's standard packaging does not support this at all. It takes a lot of work (723 LOC, in pytorch's case) to persuade distutils to do the appropriate thing.

In the short term, I think releasing a version of pystan-with-cvodes-support as a tarball which can be installed with ``pip`` seems like a good fix.

**Comment by ariddell** [comment]
There's a branch ``cvodes`` which should work now (with v2.17.1). Documentation still needs to be added.

Here's a link to the branch:

https://github.com/stan-dev/pystan/tree/cvodes

Once PyStan v2.17.1 is released, I'll add a 2.17.1-cvodes tarball to the releases page on Github.

**Pull request closed without merging**
