### PR TITLE
Feature/update to stan develop

### PR DESCRIPTION
**Pull request by syclik**
This brings the Stan branch up to the current develop branch which includes updates to the writer callbacks. 

@ariddell, let me know if you want more doc on the C++ side. Also, if you want to wait to merge this until later, that's fine and I'll keep updating the branch with additional changes to the Stan library.

### CODE REVIEW

**Comment by ariddell** [comment]
I'm going to try to do a point release and then merge this.

Is there a reason why the filtered values / sum values code is moving out of Stan? Is it going to be identical/duplicated in RStan?

**Comment by syclik** [comment]
Sounds good. There's really no rush and if you want me to close this and just leave it as a running branch until you want it, let me know. I'm happy doing that.

Re: values... good question. It might get put back in after the dust settles. It will be duplicated for RStan and for the time being, we can duplicate. We should be able to move an implementation back in once we've got final places for everything.

**Comment by ariddell** [comment]
LGTM! Thanks for all this work on the refactor (to @betanalpha as well).

**Comment by syclik** [comment]
Thanks. I'll keep the branch pretty up-to-date with Stan so there's less
work to do later.

**Pull request merged**
