### PR TITLE
Update getting_started.rst

### PR DESCRIPTION
**Pull request by monikavila**
You wrote import stan but I believe s pystan

### CODE REVIEW

**Comment by riddell-stan** [comment]
``import stan`` is correct. Starting with version 3.0, the module name is ``stan``. (The package name on PyPI is ``pystan``.)

**Comment by monikavila** [comment]
Thanks, I installed pystan using python3 and then I can import pystan but I cannot import stan.

Best,

Monika

On 29 Jul 2021, at 17:39, riddell-stan ***@***.******@***.***>> wrote:



import stan is correct. Starting with version 3.0, the module name is stan. (The package name on PyPI is pystan.)

**Comment by ahartikainen** [comment]
What OS do you have?

**Comment by monikavila** [comment]
I have Mac M1 Arm

Sent from my iPhone

On 29 Jul 2021, at 18:49, Ari Hartikainen ***@***.***> wrote:

﻿

What OS do you have?

**Comment by riddell-stan** [comment]
Unfortunately we do not build wheels for M1 or aarch64 yet.

Does stanc3 support M1? We depend on that.

**Comment by monikavila** [comment]
Thanks a lot for the clarification. I’ll check if that’s the case. Otherwise, I’ll use pystan on my computer with windows.

All the best!

Monika

Sent from my iPhone

On 29 Jul 2021, at 19:13, riddell-stan ***@***.***> wrote:

﻿

Unfortunately we do not build wheels for M1 or aarch64 yet.

Does stanc3 support M1? We depend on that.

**Pull request closed without merging**
