### PR TITLE
fix effective sample size computation

### PR DESCRIPTION
**Pull request by avehtari**
#### Summary:

fixes effective sample size computation #411

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Aki Vehtari

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by avehtari** [comment]
@ariddell code is currently working, but I haven't been able to figure out how to compare to n_eff code in stan repo, and I couldn't figure out how to run pystan tests. I need some help, please.

**Comment by ariddell** [comment]
Hi @ahartikainen is there a specific test in CmdStan or RStan which we should port to PyStan so we can verify that things are working as desired? I'm happy to help with this. Thanks for the PR!

**Comment by avehtari** [comment]
stan/src/test/unit/mcmc/chains_test.cpp has a test which uses chains from blocker.1.csv and blocker.2.csv. I have updated new n_eff reference values in chains_test.cpp. When using these same csv's, PyStan should give exactly same n_eff (as it doesn't depend on any seed or numeric accuracy).

Currently PyStan is testing n_eff only for one variable, while CmdStan tests it for many.

It would be even better to add new csv files, with such samples that for some parameters N_eff>N, and I can make such csv's later.

**Comment by avehtari** [comment]
Note that files `pystan/stan/src/test/unit/mcmc/test_csv_files/blocker.1.csv` and `pystan/tests/data/blocker1.csv` are different (same for `...2.csv'). To test it would be better to use the `blocker.1.csv` and `blocker.2.csv` in Stan repo. These files have been with more recent Stan version, and have a bit more columns before parameter columns and have more efficient samples.

So now I would need help for running N_eff computation for these more recent `blocker.1.csv` and `blocker.2.csv`.

**Comment by ariddell** [comment]
This is helpful. I'll switch things over to the new blocker csvs and
report the results.

**Comment by avehtari** [comment]
File `stan/src/test/unit/mcmc/chains_test.cpp` has reference values. Search for `n_eff <<'

**Comment by ariddell** [comment]
**rhat passes, *ess* is failing for one parameter.**

I've updated the tests in pystan/tests/test_chains.py. It should be easy to see what's going on now. Here's the test that's still problematic.

```
    def test_essnrhat(self):
        n_eff = [
            466.099, 136.553, 1196.89,
            665.131, 427.967, 582.182, 765.15,
            744.164, 319.834, 476.121, 313.209,
            588.142, 638.582, 477.636, 173.709,
            178.031, 640.858, 465.084, 561.947,
            669.612, 450.765, 406.215, 292.713,
            652.314, 1378.33, 829.726, 847.982,
            979.486, 595.743, 887.565, 228.659,
            748.785, 898.374, 219.433, 879.069,
            729.496, 716.738, 189.522, 944.547,
            841.35, 733.193, 1077.03, 469.143,
            954.924, 461.517, 506.452, 692.844, 98.0912
        ]
        lst = self.lst
        for i in range(4, len(n_eff)):
            ess = pystan.chains.ess(lst, i)
            self.assertAlmostEqual(ess, n_eff[i], delta=1)
```

It's failing on parameter index 5 which I think is ``mu.4``.

```
self.assertAlmostEqual(ess, n_eff[i], delta=1)
AssertionError: 504.28020463545545 != 427.967 within 1 delta
```

FYI, the way I test this is (from the base directory):

```bash
python3 setup.py build_ext --inplace
python3 -m unittest -v pystan/tests/test_chains.py
```

**Comment by avehtari** [comment]
You copied the old n_eff values. New ones are in develop branch and for convenience here
```
  n_eff << 466.099,136.953,1170.390,541.256,
    518.051,589.244,764.813,688.294,
    323.777,502.892,353.823,588.142,
    654.336,480.914,176.978,182.649,
    642.389,470.949,561.947,581.187,
    446.389,397.641,338.511,678.772,
    1442.250,837.956,869.865,951.124,
    619.336,875.805,233.260,786.568,
    910.144,231.582,907.666,747.347,
    720.660,195.195,944.547,767.271,
    723.665,1077.030,470.903,954.924,
    497.338,583.539,697.204,98.421;
```

But 504.280 doesn't still match... So it seems  I have an error there (I guess indexing issue)

**Comment by ariddell** [comment]
Just updated the numbers.

Here's the new error:
```
    self.assertAlmostEqual(ess, n_eff[i], delta=1)
AssertionError: 504.28020463545545 != 518.051 within 1 delta
```

**Comment by avehtari** [comment]
@ariddell in your commit you removed `blocker1.csv` and `blocker2.csv`, but did not add `blocker.1.csv` and `blocker.2.csv`. We need to have exactly same files from CmdStan.

**Comment by avehtari** [comment]
@ariddell  Did you remove one commit and then added new? It looked like that in github view, and now I have git problems in my machine...

**Comment by avehtari** [comment]
@ariddell to be more specific. You had pushed commit f532d17, and now it's gone. Please do not remove commits from a shared repo, as it messes the history and requires others to fix the conflicts in their local repo.

The modified algorithm should produce the same values at least within 6 digit accuracy. As it's not currently doing I will check my modifications.

Thanks for the help with setting up tests

**Comment by ariddell** [comment]
I did update my own commit with the new n_eff data. The commit already
did remove blocker1.csv and add blocker.1.csv (completely different files).

Sorry about overwriting my commit. I'll make a separate commit next time.

**Comment by avehtari** [comment]
```
Traceback (most recent call last):
  File "/u/77/ave/unix/proj/pystanneff/pystan/tests/test_chains.py", line 20, in setUpClass
    c1 = np.loadtxt(f1, skiprows=41, delimiter=',')[:, 4:]
  File "/u/77/ave/unix/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 898, in loadtxt
    fh = iter(open(fname))
FileNotFoundError: [Errno 2] No such file or directory: '/u/77/ave/unix/proj/pystanneff/pystan/tests/data/blocker.1.csv'
```
(After fixing the history in my repo) Still no `blocker.1.csv` in correct place. I think you forgot to include in the  commit or you forgot to include something which finds it from the correct place

**Comment by ariddell** [comment]
You're right! That's strange. I added a new commit.

**Comment by avehtari** [comment]
ok, now the results match with CmdStan and RStan with several digits accuracy

**Comment by ariddell** [comment]
Wonderful. It's a tremendous relief to have this finally fixed. Thank you!

**Pull request merged**
