### PR TITLE
docs: Add FAQ item about Windows

### PR DESCRIPTION
**Pull request by riddell-stan**
Add FAQ item about Windows.

### CODE REVIEW

**Comment by riddell-stan** [comment]
@ahartikainen How about this?

**Review by ahartikainen — APPROVED** [review]
Looks good.

**Comment by riddell-stan** [comment]
Is the bit about WSL2 technically true? PyStan 3 works without any problems? Can you use Jupyter Notebook too?

**Comment by ahartikainen** [comment]
Here are my instructions for jupyter on WSL2


## Start notebook on WSL2

On WSL2 remember to add (dynamic) IP address to the start command

`jupyter lab --ip $(hostname -I)`


Users with multiple IP addresses

`jupyter lab --ip $(echo $(hostname -I) | rev | cut -d " " -f1 | rev)`


And access the IP address, port and token combination given on the command window.

`http://192.168.222.17:8888/?token=<token-code-here>`

**Comment by riddell-stan** [comment]
Interesting. Why doesn't the default 127.0.0.1 work? Is there some Windows restriction on using that?

**Comment by ahartikainen** [comment]
Good question. Apparently nowdays localhost probably should work

https://stackoverflow.com/questions/62353890/windows-subsystem-for-linux-wsl-2-and-jupyter-lab-how-to-open-a-jupyter-note
https://docs.microsoft.com/en-us/windows/wsl/compare-versions#accessing-network-applications

(I solved that problem when WSL2 was still in preview version)

I need to test if it works "out-of-the-box" with recent Windows versions.

**Pull request merged**
