### PR TITLE
Update CVODES compilation procedure

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Update cvodes to 2.19.

Update how sundials files are selected.

#### Intended Effect:

Enable sundials.

#### How to Verify:

Run CVODES tests

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
After tests are run, this is ready.

This PR changes the `.c` compilation step for Sundials. Later can be updated for possible `.cpp`, if needed.

1st step: Compile external libs first.

This enables us to use different compiler args for C and C++. (clang bug). I needed to fork `distutils.build_clib` to enable compiler args.

This is done each time the model is compiled, but with predefined structure can be changed to use precompiled objects. (Windows `CCompiler` somehow "broken", so one needs to be careful with building and linking)

It is also possible to parallelize this by forking `CCompiler.compile` function (lower classes use `._compile`. (Threadpool)

2nd step: Compile PyStan model and link to precompiled objects.

Observations:
Numpy distutils caused some exceptions (missing structure, parameters, methods), so I don't recommend we use it for this functionality.

**Comment by ahartikainen** [comment]
@riddell-stan after this I think we could do this somehow in setup and just link against at compile time.

We probably can also use this procedure with precompiled model structure?

**Comment by riddell-stan** [comment]
How about breaking this up into two PRs. One PR updates cvodes branch to 2.19.1 (when tagged). Then we can have a separate PR which adds this fix.

**Comment by ahartikainen** [comment]
We can do that too.

I can do the first PR and then rebase this.

**Comment by riddell-stan** [comment]
FYI: 2.19.1.1 is tagged.

**Comment by riddell-stan** [comment]
With the caveat that I want to figure out a cleaner or more testable way to do this with httpstan and pystan 3, I'm fine with merging this.

Why are travis tests not being run? Or am I missing something?

**Comment by riddell-stan** [comment]
If you have a moment, I wouldn't mind understanding why numpy's build_clib / install_clib can't be used here. I recall using it in the past without too much difficulty. It does look configurable: ``https://github.com/numpy/numpy/blob/master/numpy/distutils/command/build_clib.py``

**Comment by ahartikainen** [comment]
I can re-try numpy way. It would be great to have it working.

I don't currently remember why it failed, but there was some incompatibility between distutils and numpy. Maybe the problem was that I tried to combine them together or something similar.

The best option would be 

Build Sundials objects (maybe at setup phase)
Build StanModel + link objects

**Comment by riddell-stan** [comment]
Did you want to merge this? Did the tests pass on travis?

**Comment by ahartikainen** [comment]
I think tests passed in travis. I have been too busy with arviz + bokeh, so I have not tried numpy approach.

This can be merged.

**Comment by ahartikainen** [comment]
Oh yeah, I need to update this PR a bit.

**Comment by ahartikainen** [comment]
This works excluding Python 2.7 + 64bit Windows. There is some bizarre `divide by zero` error which comes when some size check returns 0.

**Comment by ahartikainen** [comment]
I think we should merge this. I think that reason why I had problems with numpy is in that this PR is combining C and C++ sources and there might be some difference.

After 2.21 works we can re-analyze this method.

**Comment by riddell-stan** [comment]
LGTM.

**Pull request merged**
