### PR TITLE
Bugfix/fix windows compilation

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Long path problem + C++14 for msvc (not tested)

Fix long path problem by removing long paths.

#### Intended Effect:

Compilation on windows should work.

#### How to Verify:

Run appveyor.

#### Side Effects:

None

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Ari Hartikainen
By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
I had the typo `EXISTS` --> `EXIST`

And then there is the thing that `%%` is needed for batch scripts (apparently each line is running as a batch script)

**Comment by ahartikainen** [comment]
There is somewhere ∃ that is read by pip. Not sure if it's cython, numpy or Stan.

(When I find the culprit I can clean up this PR)

**Comment by riddell-stan** [comment]
Great that you found that. I think it's causing a problem with the httpstan Windows wheel too.

Here's something suspicious in my local bdist_wheel output:

```
creating build/bdist.linux-x86_64/wheel/pystan/stan/lib/stan_math/lib/boost_1.69.0/libs/wave/test/testwave/testfiles/utf8-test-ßµ™∃
```

Perhaps we can delete all directories called "test" and be done with it?

**Comment by ahartikainen** [comment]
Do we need to publish release / tag so Windows wheels get updated?

**Comment by riddell-stan** [comment]
Thanks for fixing this.

I'll do the release chores in a bit.

**Pull request merged**
