### PR TITLE
External c++

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Allow external C++ in Stan program.
If used, needs a warning that this is an experimental feature.

#### Intended Effect:

Enable external C++ code.

#### How to Verify:

Run example e.g. https://dfm.io/posts/stan-c++/

#### Side Effects:

If not used, none.

#### Documentation:

Needs update.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

@dfm

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
@dfm I think we should add this functionality to 2.x codebase.

This PR needs warning that this is an experimental feature and doc-page going through the basic steps.

**Comment by ahartikainen** [comment]
@dfm do you want to do changes to your branch, or do we create a new PR based on forked branch (I tested one and tests pass)?

**Comment by dfm** [comment]
Hi @ahartikainen, Thanks for this! Unfortunately I don't have the time to work on this at all these days (I opened the original pull request almost exactly 2 years ago 😄) so I won't be able to help substantially. Sorry about that!

**Comment by ahartikainen** [comment]
Ok, I will make another PR and transfer copyright to you. Does that sound ok?

**Comment by dfm** [comment]
Sounds great - Thanks!

**Pull request closed without merging**
