### PR TITLE
Faster extract

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Summary:

Faster extraction for long and wide formats.

Update for `to_dataframe` to include three column group ` header | parameters | diagnostics `

`header` contains `draw, chain, warmup, [permutation, chain_permutation, permutation_order, chain_permutation_order`]

where `chain_idx` --> `draw`

#### Intended Effect:

Extract takes less time, same results as before

For large problems speedups are 500x and for smaller speedup ~10x

#### How to Verify:

Test results for 1D-nD with different extraction options before and after

#### Side Effects:

Change in `to_dataframe` column names

#### Documentation:

Update for `to_dataframe` to include three column group ` header | parameters | diagnostics `

`header` contains `draw, chain, warmup, [permutation, chain_permutation, permutation_order, chain_permutation_order`]

where `chain_idx` --> `draw`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Before merge, I will test the speed difference between this implementation and the old one.

**Comment by ahartikainen** [comment]
This is much faster when the parameter count is large.

timing_pystan_old_permuted

timing_pystan_new_permuted

timing_pystan_comparison_2000_permuted

timing_pystan_relative_permuted

more tests are found here https://github.com/ahartikainen/misc_bayes/tree/master/PyStan_extract

I still need to done some testing to make sure results are identical.

**Comment by ahartikainen** [comment]
Based on the shape comparison notebook, everything looks great for extract function. I still need to double check `to_dataframe`.

Also, the last step is to remove unnecessary array creations and streamline the process.

**Comment by ahartikainen** [comment]
I did some more tweaking and now everything is faster.

I have not benchmarked `.to_dataframe()`, but had a toy example, where 50k parameters was in the range of ~1-5 second, so probably fast enough.

permuted_true

permuted_false

ndarray

**Comment by riddell-stan** [comment]
Wonderful. This will make life much better for people dealing with large fits.

**Pull request merged**
