### PR TITLE
allow diagnostic file to be specified when using VB

### PR DESCRIPTION
**Pull request by koadman**
#### Summary:
Provide API access to set the diagnostic file output path
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ariddell** [comment]
Looks great. Can you add a (superficial) test?

**Comment by koadman** [comment]
i added a test to the existing test_vb.py unit test script. Do you think that's sufficient?

**Comment by ariddell** [comment]
Thanks for this @koadman . Looks like there's one or two more changes missing in the argument handling. See the error from the tests, e.g., https://travis-ci.org/stan-dev/pystan/jobs/161128556

Let me know if you need any assistance tracking down the issue.

**Comment by koadman** [comment]
Well, looks like I had a few embarrassing mistakes in the initial commits, but should be better now. The tests on python 3.4 + 3.5 are still failing. It looks like an issue that's unrelated to this commit, but I'm not familiar enough with the pystan test stack to know.

**Comment by ariddell** [comment]
Looks great. Could you rebase/squash all these commits into one commit? Or at least squash the commits that revert changes made earlier in the PR?

**Pull request closed without merging**
