### PR TITLE
Doc explaining how to run PyStan in Atom editor on Windows

### PR DESCRIPTION
**Pull request by S-Black**
#### Summary:

I added a document that explains how to get PyStan running in Atom editor.

#### Intended Effect:

It took me some time to figure out how to run PyStan on Atom and there wasn't a straight answer anywhere which is why I created this doc to help other people who might have the same problem.

#### How to Verify:

Follow the instructions and see if it works with the sample code provided.

#### Side Effects:

It adds a text document to the docs.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: GPLv3 (http://opensource.org/licenses/GPL-3.0)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Hi, added some comments to improve and clean the instructions.

There is no hurry, you can fix them when you have time.

**Comment by S-Black** [comment]
Hi @ahartikainen,

I'm new to github and I can't see your comments. Where are they please?

Thanks

**Comment by ahartikainen** [comment]
They are commented into code (under changes tab).

**Comment by S-Black** [comment]
I feel very stupid, but I can't find your changes. I had a search and found [this](https://help.github.com/en/articles/viewing-a-pull-request-review) on the github help pages. It looks like it should show a preview of the changes or comments you made under your message to me. However, there is nothing. When I click on the Files changed tab there are only my original changes and no comments.

**Comment by ahartikainen** [comment]
Can you see the comments now?

**Comment by S-Black** [comment]
> Can you see the comments now?

Yes, thanks.

**Comment by S-Black** [comment]
I've changed the text with your suggestions @ahartikainen

**Comment by S-Black** [comment]
Fixed the spelling errors, thanks.

About ipython, this doesn't seem to be an option for windows. 

There is the hydrogen add on which is advertised as giving a similar experience in Atom as you would have in Jupyter. This has actually worked just now. Last time I tried a while ago it didn't run.

image

I guess my post is obsolete.

**Comment by ahartikainen** [comment]
LGTM

@S-Black thanks for the PR!

**Pull request merged**
