### PR TITLE
Feature/vb support

### PR DESCRIPTION
**Pull request by akucukelbir**
#### Summary:

(WIP) Support ADVI in PyStan.

#### How to Verify:

Complete the tests that Allen begun writing.

#### Reviewer Suggestions: 

@ariddell

### CODE REVIEW

**Comment by ariddell** [comment]
Thanks! Looks like it is passing mostly. Can you tell what went wrong here: https://travis-ci.org/stan-dev/pystan/jobs/125386215

**Comment by akucukelbir** [comment]
i'm surprised anything is passing!

the reason why that particular thing is failing is that the model is ill-specified. this makes advi fail its warmup stage. we can fix that by testing it on a proper model (with a well-defined posterior).

there should be still a ton to do. all i did was to write the component that writes the advi output to a temporary csv file and reads it back in. i didn't look into how to package and return it back to python, as that seemed to require some design decisions. 

i'm happy to help. that said, i suspect what would take you 10 minutes to do would take me 2 days, so if i'm going to write the rest of it, then it would be great to chat before i embark on that.

**Comment by ariddell** [comment]
I'm going to try to get the useful parts of this into 2.10.0. It would be great if one could call ``vb()`` and it would just write to disk and echo back / return the path to the csv file.

**Comment by ariddell** [comment]
Closed in favor of #235

**Pull request closed without merging**
