### PR TITLE
Use random seed in transformed data rng

### PR DESCRIPTION
**Pull request by ariddell**
Fix for #341 

Just a (failing) test for now.

### CODE REVIEW

**Comment by ahartikainen** [comment]
Do we need to test cross-chain behaviour? Do chains i and j get the same seeds?

**Comment by ariddell** [comment]
Sorry, I should have linked this as well: https://github.com/stan-dev/stan/issues/2241

The rng ignores the chain id but respects the global random seed.

**Comment by ariddell** [comment]
Not fixed in Stan yet, pushing to 2.18

**Comment by ahartikainen** [comment]
Does this branch need an updated source?
```
File "/home/travis/miniconda3/envs/env_name/lib/python3.6/site-packages/pystan/model.py", line 672, in sampling
    fit = self.fit_class(data, seed)
  File "tmp_45yk4v0/stanfit4anon_model_0bb4d474ac4c91d738cb22f6e9bccdae_2807483619347751073.pyx", line 464, in stanfit4anon_model_0bb4d474ac4c91d738cb22f6e9bccdae_2807483619347751073.StanFit4Model.__init__
AttributeError: 'stanfit4anon_model_0bb4d474ac4c91d738cb22f6e9bccdae_2807483619347751073.StanFit4Model' object has no attribute 'random_seed'
```

**Comment by ariddell** [comment]
I'll figure this out. It more than a little painful to poke around this
code. It's such a hack!

**Pull request merged**
